service: aws-node-api

frameworkVersion: "3"

custom: 
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  memorySize: 128
  versionFunctions: false
  timeout: 10
  stage: ${self:custom.secrets.NODE_ENV}
  iamRoleStatements: 
    - Effect: "Allow"
      Action: 
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"
  environment:  
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_DEV: ${self:custom.secrets.DB_DEV}
    PASS_CODE: ${self:custom.secrets.PASS_CODE}

functions:
  api:
    handler: handler.api
    description: all apis
    memorySize: 128
    timeout: 600
    events:
      - http:
          path: api/{path}
          method: any
          cors: true # cross origin resource sharing
      - http:
          path: api/{path}/{path2}
          method: any
          cors: true

  userlogin:
    handler: handler.userlogin
    memorySize: 128
    timeout: 600
    events:
      - http:
          path: userlogin
          method: any
          cors: true

  firemail:
    handler: sendemail.firemail
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: firemail
          method: any
          cors: true

plugins:
  - serverless-offline
